---
common_packages:
  - libcmocka-dev
  - libcmocka0
  - make
  - cmake
  - valgrind
  - jq
  - libfdt-dev

common_packages_dev:
  - gdb
  - meson
  - libkmod-dev
  - libdrm-dev
  - libunwind-dev
  - libdw-dev
  - libproc2-dev
  - libcairo2-dev
  - libxmlrpc-core-c3-dev
  - gtk-doc-tools
  - libjson-c-dev
  - liboping-dev
  - libxv-dev
  - libxrandr-dev
  - peg
  - libatomic-ops-dev
  - libpciaccess-dev
  - libgsl-dev
  - libalsa-ocaml-dev
  - x11proto-dri2-dev
  - xutils-dev
  - python3-docutils
  - flex
  - bison
  - openmpi-bin
  - build-essential
  - gcc
  - libnl-3-dev
  - libnl-route-3-dev
  - ninja-build
  - pkg-config
  - valgrind
  - python3-dev
  - pandoc
  - libsystemd-dev
  - python3-pip
  - autotools-dev
  - zip
  - yasm
  - ccache
  - nasm
  - numactl
  - sshpass
  - protobuf-compiler
  - maven
  - g++
  - google-perftools
  - googletest
  - yarn
  - texinfo
  - uuid-dev
  - xxd
  - python3-venv
  - automake
  - device-tree-compiler
  - libboost-dev
  - libboost-filesystem-dev
  - libboost-program-options-dev
  - libboost-random-dev
  - libboost-regex-dev
  - libcurl4-gnutls-dev
  - libelf-dev
  - libgl1-mesa-dev
  - libgmp3-dev
  - libncurses6
  - libnuma-dev
  - libopencv-core-dev
  - libopencv-highgui-dev
  - libopencv-imgproc-dev
  - libsox-dev
  - libssl-dev
  - libxslt1-dev
  - libyaml-cpp-dev
  - libzmq3-dev
  - libopenmpi-dev
  - libgtest-dev
  - net-tools
  - libmkl-dev
  - libcairo-dev
  - libpixman-1-dev
  - libudev-dev
  - cron
  - imagemagick
  - systemd-coredump