Vagrant.configure("2") do |config|
  if "#{config.vm.guest}" == "__UNSET__VALUE__"
    config.vm.guest = :centos
    puts "Forced os #{config.vm.guest}"
  end
  config.vm.boot_timeout = 600
  config.vm.define "source", autostart: false do |source|
    source.vm.box = "almalinux/9"
    config.ssh.insert_key = false
    source.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      if source.vm.box.include?("uefi")
        domain.loader = '/usr/share/OVMF/OVMF_CODE_4M.fd'
        domain.nvram = '/var/lib/libvirt/qemu/nvram/OVMF_VARS_4M.fd'
      end
    end
  end
    config.vm.define "output" do |output|
    output.vm.box = "almalinux/9"
    output.vm.box_url = "file://package.box"
    config.ssh.insert_key = false
    output.vm.provider :libvirt do |destination|
      destination.memory = 4096
      destination.cpus = 4
      if destination.vm.box.include?("uefi")
        destination.loader = '/usr/share/OVMF/OVMF_CODE_4M.fd'
        destination.nvram = '/var/lib/libvirt/qemu/nvram/OVMF_VARS_4M.fd'
      end
    end
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
