ftp_proxy: http://proxy.example.com:3128
http_proxy: http://proxy.example.com:3128
https_proxy: http://proxy.example.com:3128
no_proxy: '127.0.0.1,localhost,.example.com,10.0.0.0/8,192.168.0.0/16'
proxy_socks: 'proxy.example.com:1080'

docker_proxy_dir: "/etc/systemd/system/docker.service.d"
docker_proxy_file: "/etc/systemd/system/docker.service.d/http-proxy.conf"

apt_conf_file: "/etc/apt/apt.conf.d/20proxy"
